stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: rivoltacloud:${CICD_GIT_TAG}
      pushRemote: true
      registry: index.docker.io
timeout: 60
notification: {}
