stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: rivoltacloud:${CICD_GIT_TAG}
      registry: 127.0.0.1:34653
timeout: 60
notification: {}
