stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: grivolta/rivoltacloud:${CICD_GIT_TAG}
      pushRemote: true
      registry: index.docker.io
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./rivoltacloud.yaml
timeout: 60
notification: {}
