apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: deployrivoltacloud
  namespace: sito
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-sito-deployrivoltacloud
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2019-03-22T09:41:44Z"
        field.cattle.io/ports: '[[{"containerPort":80,"dnsName":"deployrivoltacloud","kind":"ClusterIP","name":"80tcp802","protocol":"TCP","sourcePort":80}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-sito-deployrivoltacloud
    spec:
      containers:
      - image: grivolta/rivoltacloud:${CICD_GIT_TAG}
        imagePullPolicy: Always
        name: deployrivoltacloud
        ports:
        - containerPort: 80
          name: 80tcp802
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          procMount: Default
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: dockergrivoltacloud
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
